### ISSUE TITLE
Issues in the conversion to pdf

### ISSUE THREAD

**Issue by riccardotommasini** [bsdz/remarkable-layers#11]
It seesm that the svg conversion is broken.
the script ignores some attributes like h/v/l (lowercase), and some exception are raised when non-floats are encountered.

**Comment by bsdz** [comment]
Quite possible yes.

**Comment by riccardotommasini** [comment]
I did a few simpler tests, trying to load a simple SVG file, move it to .rm and then back to SVG.
Unfortunately, the process seems to fail. 

I recognized the source of the bug as the svg_to_points method.
Can you explain the rationale of the conversion, I could not map it to the documentation on .lines data.


thanks in advance
