### ISSUE TITLE
Problem in running script

### ISSUE THREAD

**Issue by mtagliazucchi** [bsdz/remarkable-layers#16]
When trying to run `rmlines_pdf_converter` I get the error 
`ModuleNotFoundError: No module named 'scripts.pdf_converter'`
How can i solve?

**Comment by lorenzosquadrani** [comment]
It is a script, not a module silly mcPussy

**Comment by gorkan** [comment]
But where is this script located? If I can not find it in the folder of the project. I did  install first every package from the dependency list and did then the poetry install --no-dev. But I still can not find a file with the name rmlines_pdf_converter.

**Comment by bsdz** [comment]
These scripts are mapped/created when installing the package. We use poetry's pyproject.toml to do this similar to the more traditional setup.py method.
