### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ahill187** [bsdz/remarkable-layers#19]
I followed the install instructions, but received an error about installing `potrace`. 

I followed the instructions here: https://github.com/bsdz/pypotrace. Then the install worked. I would add this to the README 😃 

### System/Versions

OS: MacOSX Big Sur
Python: 3.7

**Comment by bsdz** [comment]
Ah yes sorry about that. I should have made that clear. As mentioned in another issue I am archiving project so not much point in adjusting the README now.
