### ISSUE TITLE
pdf_converter: could not convert string to float

### ISSUE THREAD

**Issue by harrylepotter** [bsdz/remarkable-layers#2]
Hi there! 
I'm trying to convert pdf files on a mac. I seem to be hitting an error on all of the documents i've attempted to try. Here's the stack trace:

`
INFO:__main__:Processing PDF file '/Users/bdavey/Desktop/prints/ben.pdf'
INFO:__main__:Extracting to SVG page 1
INFO:__main__:Unable to revert mtime: /Library/Fonts

INFO:__main__:verbs_action: Invalid verb: com.klowner.filter.applytransform.noprefs
InkscapeApplication::close_document: Window vector not empty!

INFO:__main__:Extracting to SVG page 2
INFO:__main__:
INFO:__main__:verbs_action: Invalid verb: com.klowner.filter.applytransform.noprefs
InkscapeApplication::close_document: Window vector not empty!

INFO:__main__:Extracting to SVG page 3
INFO:__main__:
INFO:__main__:verbs_action: Invalid verb: com.klowner.filter.applytransform.noprefs
InkscapeApplication::close_document: Window vector not empty!

INFO:__main__:Creating Rm Lines file for /Users/bdavey/Desktop/prints/ben/page_1.svg
Traceback (most recent call last):
  File "scripts/pdf_converter.py", line 399, in <module>
    generate_rmlines_and_upload(out_dir)
  File "scripts/pdf_converter.py", line 339, in generate_rmlines_and_upload
    rm = RMLines.from_svg(f.open("rb"))
  File "/Users/bdavey/dev/remarkable-layers/rmlines/rmobject/lines.py", line 45, in from_svg
    return svg_to_rmlines(buffer)
  File "/Users/bdavey/dev/remarkable-layers/rmlines/svg.py", line 91, in svg_to_rmlines
    layer.extend(svg_path_to_strokes(path.attrib["d"]))
  File "/Users/bdavey/dev/remarkable-layers/rmlines/svg.py", line 58, in svg_path_to_strokes
    points = svg_path_d_to_points(d)
  File "/Users/bdavey/dev/remarkable-layers/rmlines/svg.py", line 31, in svg_path_d_to_points
    point = [float(args), point[1]]
ValueError: could not convert string to float: '1.8125 l 0.018555 0.2988285 0.05957 0.2636715 0.09668 0.2348634'
`

inkscape version info:
`inkscape --version
Inkscape 1.0.1 (c497b03c, 2020-09-10)
    Pango version: 1.43.0
`

Thanks for the amazing work on this!

**Comment by bsdz** [comment]
I'm not sure really. I am also using the same version of Inkscape as you are (albeit on Ubuntu Linux). 

It might be the missing applytransforms plugin. I had thought it came bundled with Inkscape 1.0+. Perhaps try installing it manually from [their github repo](https://github.com/Klowner/inkscape-applytransforms) One can confirm it's available with following commands:

```bash
$ inkscape --verb-list | grep klowner
com.klowner.filter.applytransform: Apply Transform
com.klowner.filter.applytransform.noprefs: Apply Transform (No preferences)
```

**Comment by harrylepotter** [comment]
I reckon that might be it. Seems to be missing from my dist. I'll try rebuilding with the applytransformations plugin.

Thanks for all of the amazing work once again. I'm so excited to be able to select content from pdfs.

**Comment by harrylepotter** [comment]
can confirm that this works on mac, albeit the applytransformations plugin needs to be installed manually from https://github.com/Klowner/inkscape-applytransforms

Thanks a million for your help!
