### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts'

### ISSUE THREAD

**Issue by ahill187** [bsdz/remarkable-layers#20]
When I try to run:
```
rmlines_pdf_converter my_file.pdf --first 10 --last 25
```
I get this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/rmlines_pdf_converter", line 5, in <module>
    from scripts.pdf_converter import main
ModuleNotFoundError: No module named 'scripts'
```

### System/Versions

OS: MacOS Big Sur
Python: 3.7

**Comment by bsdz** [comment]
Not sure why that is happening. Perhaps I've overlooked something with how poetry sets up the scripts on MacOS. It seemed to work on Ubuntu. As workaround, you could just download the script from this repo locally and use.  Tbh I am going to archive this project as I am not using it. Feel free to fork & adjust if any use to you :)
