### ISSUE TITLE
Cloud upload fails due to out-of-date rmapy dependency

### ISSUE THREAD

**Issue by YakBarber** [bsdz/remarkable-layers#21]
My scripts recently started failing at the `upload` step in `rmlines.rmcloud.upload_rm_doc` with a 401, despite `client.is_auth()==True`. 

I have done some digging, and it seems due to the reliance on a custom fork of `rmapy 0.2.2`. Updating that dependency to upstream, which is `0.2.5`, resolved my issue.

However, I'm unsure if any changes in the fork are still needed. If those changes have made it upstream already I'm happy to submit a PR to update the dependency.

**Comment by YakBarber** [comment]
The issue seems to be related to a ReMarkable URL change, see https://github.com/subutux/rmapy/pull/24

**Comment by bsdz** [comment]
Yes that's likely. I originally had to fork that project to fix a typo and my fork won't be maintained. Actually I am going to archive this project as I am not using it. Feel free to fork if any use to you :)
