### ISSUE TITLE
Output file generated is always empty

### ISSUE THREAD

**Issue by rafaelsgirao** [bsdz/remarkable-layers#4]
Hi,
As I said in my pull request I can't seem to get this working - pdf_converter script always generates a cannot convert to float error, I'm guessing because of something changing on inkscape's part, because SVGs generated there always come up as empty or only having a few random lines. (though manually exporting SVGs in inkscape works)

I tried getting around that issue and made a script to convert SVG to RM and upload it, but the result always comes up as empty.
The same result occurs when I manually put SVG files instead of letting the script generate them, it uploads them, but when I go view them on my Remarkable only the base template appears, nothing of my document.
Any thoughts on this?
Thanks!

**Comment by bsdz** [comment]
The PDF converter is quite a complex script with several moving parts. Have you tried the example scripts pen_gallery.py and samples.py? They don't require inkscape and will at least tell you if you can upload basic SVGs.

**Comment by Barabazs** [comment]
I'm also having some issues with the script. I can't really figure out what the issue is with my PDF files.
Here are some examples:

What works for me: 
https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf 
http://www.orimi.com/pdf-test.pdf

What does not work for me:
[test.pdf](https://github.com/bsdz/remarkable-layers/files/5528999/test.pdf)

Output is:
```
Traceback (most recent call last):
  File "scripts/pdf_converter.py", line 399, in <module>
    extract_svg_page(
  File "scripts/pdf_converter.py", line 265, in extract_svg_page
    prepare_images(stage_svg)
  File "scripts/pdf_converter.py", line 137, in prepare_images
    trans_matrix = parse_transform(use.attrib["transform"])
  File "src/lxml/etree.pyx", line 2479, in lxml.etree._Attrib.__getitem__
KeyError: 'transform'
```

**Comment by bsdz** [comment]
> I'm also having some issues with the script. I can't really figure out what the issue is with my PDF files.
> Here are some examples:
> 
> What works for me:
> https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf
> http://www.orimi.com/pdf-test.pdf
> 
> What does not work for me:
> [test.pdf](https://github.com/bsdz/remarkable-layers/files/5528999/test.pdf)
> 
> Output is:
> 
> ```
> Traceback (most recent call last):
>   File "scripts/pdf_converter.py", line 399, in <module>
>     extract_svg_page(
>   File "scripts/pdf_converter.py", line 265, in extract_svg_page
>     prepare_images(stage_svg)
>   File "scripts/pdf_converter.py", line 137, in prepare_images
>     trans_matrix = parse_transform(use.attrib["transform"])
>   File "src/lxml/etree.pyx", line 2479, in lxml.etree._Attrib.__getitem__
> KeyError: 'transform'
> ```

This looks like a slightly different issue. I'm glad it's working for you for some files. There must be various ways of embedding images in PDFs and I only considered a small subset of them. Not sure what to suggest here really. It would involve looking at the underlying SVG and adjusting the code to support it.

**Comment by Barabazs** [comment]
I probably should have opened a new issue.

I do however have the problem that an empty notebook is uploaded when I manually convert the pdf to svg and then try to run pdf_converter.py (without overwriting the svg).

**Comment by bsdz** [comment]
> I probably should have opened a new issue.
> 
> I do however have the problem that an empty notebook is uploaded when I manually convert the pdf to svg and then try to run pdf_converter.py (without overwriting the svg).

Do the other sample scripts upload non-empty documents?

https://github.com/bsdz/remarkable-layers/issues/4#issuecomment-725573776

**Comment by Barabazs** [comment]
> > I probably should have opened a new issue.
> > I do however have the problem that an empty notebook is uploaded when I manually convert the pdf to svg and then try to run pdf_converter.py (without overwriting the svg).
> 
> Do the other sample scripts upload non-empty documents?
> 
> [#4 (comment)](https://github.com/bsdz/remarkable-layers/issues/4#issuecomment-725573776)

Do you mean samples.py ? (That correctly uploads the samle notebooks you provided)
If you mean the documents that worked with pdf_converter.py: 
I've tested it right now and it would also upload an empty document.

**Comment by bsdz** [comment]
> > Do the other sample scripts upload non-empty documents?
> > [#4 (comment)](https://github.com/bsdz/remarkable-layers/issues/4#issuecomment-725573776)
> 
> Do you mean samples.py ? (That correctly uploads the samle notebooks you provided)
> If you mean the documents that worked with pdf_converter.py:
> I've tested it right now and it would also upload an empty document.

Good to hear samples.py uploads correctly. How about pen_gallery.py? That converts svg to rm. It's not as complicated as the pdf_converter.py but might provide a clue as to where the empty rm file is being generated.

**Comment by Barabazs** [comment]
pen_gallery.py also works. It uploads a notebook with Pen.PAINT_BRUSH_, Width.SMALL etc

**Comment by Barabazs** [comment]
I've been going through the code and I suppose the manually converted SVG is not "simple" as required by your code.

**Comment by rafaelsgirao** [comment]
I figured it out, turns out it was the same problem as #2 
Manually installing the verbs in that repo and re-running pdf_converter.py generated correct SVGs and uploads them.
I think this is something worth adding to the README since I guess most versions of Inkscape don't come with it now.

And yes, manually converted SVGs from another source will most likely not work because there is a lot of post-processing going on in that script.

Thanks!
