### ISSUE TITLE
Minor: removing square grid layers in output .rm file

### ISSUE THREAD

**Issue by croci** [bsdz/remarkable-layers#6]
Hi There,

When using pdf_converter.py the exported .rm file always has two extra layers with a square grid. It is easy to remove them manually, but I do not understand why they are there when the original pdf/svg file did not have them. Would it be possible to not add them by default?

Thanks a lot for a great software btw! This is the only module I could find that supports pdf/svg to .rm conversion and is extremely useful!

**Comment by bsdz** [comment]
Thanks.  I can make those layers optional. I use those layers for copying formulae from the converted pdf to my own summary notebook. There are two halves so one can view the top of the document and drag to the bottom notes layer & vice versa. Tbh it's still too cumbersome for my liking.

**Comment by croci** [comment]
Ah, now I understand why they are there, I do see the appeal, but yes having the option to not include the grid layers would be great, thanks!

**Comment by bsdz** [comment]
I've added an command line option that will exclude the note taking grid layers.eg

```bash
rmlines_pdf_converter --exclude-grid-layers False --first 1 --last 10 /tmp/some_doc.pdf
```

Thanks for the suggestion.

**Comment by croci** [comment]
Brilliant, thanks!
