### ISSUE TITLE
numpy missing from requirements?

### ISSUE THREAD

**Issue by micheledicosmo** [bsdz/remarkable-layers#9]
I add to manually install numpy when installing requisites with pip as it got blocked with 'numpy missing'

**Comment by croci** [comment]
The developer does not use pip to install but poetry. Try to install numpy manually in the venv before installing the rest of the dependency. See what I have done here https://github.com/croci/remarkable-layers/tree/large_trees_and_venv

**Comment by bsdz** [comment]
Actually I updated package to allow using pip back in December. I also submitted a PR to pypotrace to support simpler installation although it wasn't accepted at first [someone else kindly pinned](https://github.com/flupke/pypotrace/pull/35) the versions for the author; so I need to update dependencies to use the main pypotrace and drop my fork.

**Comment by alex20465** [comment]
What is "poetry" ? ....  'Python packaging and dependency management made easy '


```
$ poetry install

Creating virtualenv rmlines-06qrxIlP-py3.8 in /home/xxxx/.cache/pypoetry/virtualenvs

  ModuleNotFoundError

  No module named 'virtualenv.seed.via_app_data'

  at <frozen importlib._bootstrap>:973 in _find_and_load_unlocked
```

I know this doesn't help, but I just post this for FUN.
